log_info("akhenaten: localization_en config started")

localization_en = [
     {key:"#TR_NO_PATCH_TITLE", text:"Patch ???"},
     {key:"#TR_NO_PATCH_MESSAGE", text:"Your Pharahoh installation does not have the 1.2.1.0 patch installed. "},
     {key:"#TR_MISSING_FONTS_TITLE", text:"Missing fonts"},
     {key:"#TR_MISSING_FONTS_MESSAGE", text:"Pharahoh installation requires extra font files. "},
     {key:"#TR_NO_EDITOR_TITLE", text:"Editor not installed"},
     {key:"#TR_NO_EDITOR_MESSAGE", text:"Your Pharahoh installation does not contain the editor files. "},
     {key:"#TR_INVALID_LANGUAGE_TITLE", text:"Invalid language directory"},
     {key:"#TR_INVALID_LANGUAGE_MESSAGE", text:"The directory you selected does not contain a valid language pack. Please check the log for errors."},
     {key:"#TR_BUTTON_OK", text:"OK"},
     {key:"#TR_BUTTON_CANCEL", text:"Cancel"},
     {key:"#TR_BUTTON_RESET_DEFAULTS", text:"Reset defaults"},
     {key:"#TR_BUTTON_CONFIGURE_HOTKEYS", text:"Configure hotkeys"},
     {key:"#TR_BUTTON_NEXT", text:"+"},
     {key:"#TR_BUTTON_PREV", text:"-"},
     {key:"#TR_CONFIG_TITLE", text:"Enhanced settings"},
     {key:"#TR_CONFIG_LANGUAGE_LABEL", text:"Language:"},
     {key:"#TR_CONFIG_LANGUAGE_DEFAULT", text:"(default)"},
     {key:"#TR_CONFIG_PAGE_LABEL", text:"Page"},
     {key:"#TR_CONFIG_HEADER_UI_CHANGES", text:"User interface changes"},
     {key:"#TR_CONFIG_HEADER_GAMEPLAY_CHANGES", text:"Gameplay changes"},
     {key:"#TR_CONFIG_HEADER_GODS_CHANGES", text:"Gods changes"},
     {key:"#TR_CONFIG_HEADER_BUILDING_CHANGES", text:"Building changes"},
     {key:"#TR_CONFIG_HEADER_RESOURCE_CHANGES", text:"Resource changes"},
     {key:"#TR_CONFIG_SHOW_INTRO_VIDEO", text:"Play intro videos"},
     {key:"#TR_CONFIG_HIDE_NEW_GAME_TOP_MENU", text:"Hide top menu new game button"},
     {key:"#TR_CONFIG_SAVE_YEAR_KINGDOME_RATING", text:"Save kingdom rating on yearly update"},
     {key:"#TR_CONFIG_SIDEBAR_INFO", text:"Extra information in the control panel"},
     {key:"#TR_CONFIG_SMOOTH_SCROLLING", text:"Enable smooth scrolling"},
     {key:"#TR_CONFIG_VISUAL_FEEDBACK_ON_DELETE", text:"Improve visual feedback when clearing land"},
     {key:"#TR_CONFIG_ALLOW_CYCLING_TEMPLES", text:"Allow building each temple in succession"},
     {key:"#TR_CONFIG_SHOW_WATER_STRUCTURE_RANGE", text:"Show range when building reservoirs, fountains and wells"},
     {key:"#TR_CONFIG_SHOW_CONSTRUCTION_SIZE", text:"Show draggable construction size"},
     {key:"#TR_CONFIG_HIGHLIGHT_LEGIONS", text:"Highlight legion on cursor hover"},
     {key:"#TR_CONFIG_ROTATE_MANUALLY", text:"Rotate Gatehouse and Triumph Arch by hotkey"},
     {key:"#TR_CONFIG_FIX_IMMIGRATION_BUG", text:"Fix immigration bug on very hard"},
     {key:"#TR_CONFIG_FIX_100_YEAR_GHOSTS", text:"Fix 100-year-old ghosts"},
     {key:"#TR_CONFIG_FIX_EDITOR_EVENTS", text:"Fix Emperor change and survival time in custom missions"},
     {key:"#TR_CONFIG_DRAW_WALKER_WAYPOINTS", text:"Draw walker waypoints on overlay after right clicking on a building"},
     {key:"#TR_CONFIG_ZOOM_STEPPED", text:"Enable zoom (can be slow, uses more RAM)"},
     {key:"#TR_CONFIG_COMPLETE_RATING_COLUMNS", text:"Fix uncompleted rating columns on low targets"},
     {key:"#TR_CONFIG_GRANDFESTIVAL", text:"Grand festivals allow extra blessing from a god"},
     {key:"#TR_CONFIG_JEALOUS_GODS", text:"Disable jealousness of gods"},
     {key:"#TR_CONFIG_GLOBAL_LABOUR", text:"Enable global labour pool"},
     {key:"#TR_CONFIG_SCHOOL_WALKERS", text:"Extend school walkers range"},
     {key:"#TR_CONFIG_RETIRE_AT_60", text:"Change citizens' retirement age from 50 to 60"},
     {key:"#TR_CONFIG_FIXED_WORKERS", text:"Fixed worker pool - 38% of population"},
     {key:"#TR_CONFIG_EXTRA_FORTS", text:"Allow building 4 extra forts"},
     {key:"#TR_CONFIG_WOLVES_BLOCK", text:"Block building around wolves"},
     {key:"#TR_CONFIG_DYNAMIC_GRANARIES", text:"Block unconnected granary roads"},
     {key:"#TR_CONFIG_MORE_STOCKPILE", text:"Houses stockpile more goods from market"},
     {key:"#TR_CONFIG_NO_BUYER_DISTRIBUTION", text:"Buying market ladies don't distribute goods"},
     {key:"#TR_CONFIG_IMMEDIATELY_DELETE_BUILDINGS", text:"Immediately destroy buildings"},
     {key:"#TR_CONFIG_GETTING_GRANARIES_GO_OFFROAD", text:"Cart pushers from getting granaries can go offroad"},
     {key:"#TR_CONFIG_GRANARIES_GET_DOUBLE", text:"Double the capacity of cart pushers from getting granaries"},
     {key:"#TR_CONFIG_TOWER_SENTRIES_GO_OFFROAD", text:"Tower sentries don't need road access from barracks"},
     {key:"#TR_CONFIG_FARMS_DELIVER_CLOSE", text:"Farms and wharves deliver only to nearby granaries"},
     {key:"#TR_CONFIG_DELIVER_ONLY_TO_ACCEPTING_GRANARIES", text:"Food isn't delivered to getting granaries"},
     {key:"#TR_CONFIG_ALL_HOUSES_MERGE", text:"All houses merge"},
     {key:"#TR_CONFIG_WINE_COUNTS_IF_OPEN_TRADE_ROUTE", text:"Open trade route count as providing different wine type"},
     {key:"#TR_CONFIG_RANDOM_COLLAPSES_TAKE_MONEY", text:"Randomly collapsing clay pits and iron mines take some money instead"},
     {key:"#TR_CONFIG_MULTIPLE_BARRACKS", text:"Allow building multiple barracks."},
     {key:"#TR_CONFIG_NOT_ACCEPTING_WAREHOUSES", text:"Warehouses don't accept anything when built"},
     {key:"#TR_CONFIG_HOUSES_DONT_EXPAND_INTO_GARDENS", text:"Houses don't expand into gardens"},
     {key:"#TR_CONFIG_FIX_IRRIGATION_RANGE", text:"Fix irrigation range"},
     {key:"#TR_CONFIG_FIX_FARM_PRODUCING", text:"Fix farm producing"},
     {key:"#TR_CONFIG_CAMERA_KEEP_INERTIA", text:"Camera keep inertia"},
     {key:"#TR_CONFIG_UNDERSTAFFED_ACCEPT_GOODS", text:"Understaffed accept goods"},
     {key:"#TR_CONFIG_MULTIPLE_TEMPLE_COMPLEXES", text:"Multiple temple complexes"},
     {key:"#TR_CONFIG_MULTIPLE_MONUMENTS", text:"Multiple monuments"},
     {key:"#TR_CONFIG_SOIL_DEPLETION", text:"Soil depletion"},
     {key:"#TR_CONFIG_MULTIPLE_GATHERERS", text:"Multiple gatherers"},
     {key:"#TR_CONFIG_FIREMAN_RETURNING", text:"Fireman returning after fight fire"},
     {key:"#TR_CONFIG_CART_SPEED_DEPENDS_QUANTITY", text:"Cart speed depends from quantity resource"},
     {key:"#TR_CONFIG_CH_CITIZEN_ROAD_OFFSET", text:"Use different offsets for citizens in road"},
     {key:"#TR_CONFIG_CH_WORK_CAMP_ONE_WORKER_PER_MONTH", text:"Work camp spawn one worker per month"},
     {key:"#TR_CONFIG_CH_CLAY_PIT_FIRE_RISK_REDUCED", text:"Clay pit fire risk reduced"},
     {key:"#TR_CONFIG_CITY_HAS_ANIMALS", text:"City has animals" },
     {key:"#TR_CONFIG_GOLDMINE_TWICE_PRODUCTION", text:"Goldmine twice production"},
     {key:"#TR_CONFIG_NEW_TAX_COLLECTION_SYSTEM", text:"New tax collection system"},
     {key:"#TR_CONFIG_SMALL_HUT_NOT_CREATE_EMIGRANT", text:"Small hut houses not create enimgrant"},
     {key:"#TR_CONFIG_DELIVERY_BOY_GOES_TO_MARKET_ALONE", text:"Delivery boy goes to market alone"},
     {key:"#TR_CONFIG_RELIGION_COVERAGE_INFLUENCE_SENTIMENT", text:"Religion coverage influence sentiment"},
     {key:"#TR_CONFIG_MONUMENTS_INFLUENCE_SENTIMENT", text:"Monuments influence sentiment"},
     {key:"#TR_CONFIG_WELL_RADIUS_DEPENDS_MOISTURE", text:"Well radius depends from moisture"},
     {key:"#TR_CONFIG_ENTER_POINT_ON_NEAREST_TILE", text:"Building entrance on the neareast tile"},
     {key:"#TR_CONFIG_FISHING_WHARF_SPAWN_BOATS", text:"Fishing wharf spawn boats"},
     {key:"#TR_CONFIG_CITY_FLOTSAM_ENABLED", text:"City flotsam enabled"},
     {key:"#TR_CONFIG_COPPER_NEAR_MOUNTAINS", text:"Copper mine can build near mountains"},
     {key:"#TR_CONFIG_RECRUITER_NOT_NEED_FORTS", text:"Recruiter not need forts"},
     {key:"#TR_CONFIG_BUILDING_CLOSEST_ROAD", text:"Building access tile closest road"},
     {key:"#TR_CONFIG_FLOODPLAIN_RANDOM_GROW", text:"Floodplain random grow"},
     {key:"#TR_CONFIG_DRAW_FPS", text:"Draw FPS"},
     {key:"#TR_CONFIG_HIGHLIGHT_TOP_MENU_HOVER", text:"Highlight Top Menu Items"},
     {key:"#TR_CONFIG_EMPIRE_CITY_OLD_NAMES", text:"Show Old Names for city on empire map"},
     {key:"#TR_CONFIG_DRAW_CLOUD_SHADOWS", text:"Draw cloud shadows (experimental)"},
     {key:"#TR_CONFIG_HEADER_SCENARIO_CHANGES", text:"Change scenarios"},
     {key:"#TR_CONFIG_HEADER_RESOURCES", text:"Change resources"},
     {key:"#TR_CONFIG_ANIMALS", text:"Change animals"},
     {key:"#TR_CONFIG_FLOTSAM", text:"Flotsam"},
     {key:"#TR_GAMEPLAY_GOD_DISABLED", text:"God disabled"},
     {key:"#TR_HOTKEY_TITLE", text:"Hotkeys configuration"},
     {key:"#TR_HOTKEY_LABEL", text:"Hotkey"},
     {key:"#TR_HOTKEY_ALTERNATIVE_LABEL", text:"Alternative"},
     {key:"#TR_HOTKEY_HEADER_ARROWS", text:"Arrow keys"},
     {key:"#TR_HOTKEY_HEADER_GLOBAL", text:"Global hotkeys"},
     {key:"#TR_HOTKEY_HEADER_CITY", text:"City hotkeys"},
     {key:"#TR_HOTKEY_HEADER_ADVISORS", text:"Advisors"},
     {key:"#TR_HOTKEY_HEADER_OVERLAYS", text:"Overlays"},
     {key:"#TR_HOTKEY_HEADER_BOOKMARKS", text:"City map bookmarks"},
     {key:"#TR_HOTKEY_HEADER_EDITOR", text:"Editor"},
     {key:"#TR_HOTKEY_HEADER_BUILD", text:"Construction hotkeys"},
     {key:"#TR_HOTKEY_ARROW_UP", text:"Up"},
     {key:"#TR_HOTKEY_ARROW_DOWN", text:"Down"},
     {key:"#TR_HOTKEY_ARROW_LEFT", text:"Left"},
     {key:"#TR_HOTKEY_ARROW_RIGHT", text:"Right"},
     {key:"#TR_HOTKEY_TOGGLE_FULLSCREEN", text:"Toggle fullscreen"},
     {key:"#TR_HOTKEY_CENTER_WINDOW", text:"Center window"},
     {key:"#TR_HOTKEY_RESIZE_TO_640", text:"Resize window to 640x480"},
     {key:"#TR_HOTKEY_RESIZE_TO_800", text:"Resize window to 800x600"},
     {key:"#TR_HOTKEY_RESIZE_TO_1024", text:"Resize window to 1024x768"},
     {key:"#TR_HOTKEY_SAVE_SCREENSHOT", text:"Save screenshot"},
     {key:"#TR_HOTKEY_SAVE_CITY_SCREENSHOT", text:"Save full city screenshot"},
     {key:"#TR_HOTKEY_LOAD_FILE", text:"Load file"},
     {key:"#TR_HOTKEY_SAVE_FILE", text:"Save file"},
     {key:"#TR_HOTKEY_INCREASE_GAME_SPEED", text:"Increase game speed"},
     {key:"#TR_HOTKEY_DECREASE_GAME_SPEED", text:"Decrease game speed"},
     {key:"#TR_HOTKEY_TOGGLE_PAUSE", text:"Toggle pause"},
     {key:"#TR_HOTKEY_CYCLE_LEGION", text:"Cycle through legions"},
     {key:"#TR_HOTKEY_ROTATE_MAP_LEFT", text:"Rotate map left"},
     {key:"#TR_HOTKEY_ROTATE_MAP_RIGHT", text:"Rotate map right"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_LABOR", text:"Labor advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_MILITARY", text:"Military advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_IMPERIAL", text:"Imperial advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_RATINGS", text:"Ratings advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_TRADE", text:"Trade advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_POPULATION", text:"Population advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_HEALTH", text:"Health advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_EDUCATION", text:"Education advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_ENTERTAINMENT", text:"Entertainment advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_RELIGION", text:"Religion advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_FINANCIAL", text:"Financial advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_CHIEF", text:"Chief advisor"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_HOUSING", text:"Housing advisor"},
     {key:"#TR_HOTKEY_TOGGLE_OVERLAY", text:"Toggle current overlay"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_WATER", text:"Show water overlay"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_FIRE", text:"Show fire overlay"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_DAMAGE", text:"Damage overlay"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_CRIME", text:"Crime overlay"},
     {key:"#TR_HOTKEY_ROTATE_BUILDING", text:"Rotate building"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_PROBLEMS", text:"Problems overlay"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_1", text:"Go to bookmark 1"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_2", text:"Go to bookmark 2"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_3", text:"Go to bookmark 3"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_4", text:"Go to bookmark 4"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_1", text:"Set bookmark 1"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_2", text:"Set bookmark 2"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_3", text:"Set bookmark 3"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_4", text:"Set bookmark 4"},
     {key:"#TR_HOTKEY_EDITOR_TOGGLE_BATTLE_INFO", text:"Toggle battle info"},
     {key:"#TR_HOTKEY_EDIT_TITLE", text:"Press new hotkey"},
     {key:"#TR_BUILDING_ROADBLOCK", text:"Roadblock"},
     {key:"#TR_BUILDING_ROADBLOCK_DESC", text:"Roadblock stops loitering citizens."},
     {key:"#TR_HEADER_HOUSING", text:"Housing"},
     {key:"#TR_ADVISOR_HOUSING_ROOM", text:"City housing has room available for"},
     {key:"#TR_ADVISOR_HOUSING_NO_ROOM", text:"There is no room available in city housing."},
     {key:"#TR_ADVISOR_RESIDENCES_DEMANDING_POTTERY", text:"Residences demanding pottery"},
     {key:"#TR_ADVISOR_RESIDENCES_DEMANDING_FURNITURE", text:"Residences demanding furniture"},
     {key:"#TR_ADVISOR_RESIDENCES_DEMANDING_OIL", text:"Residences demanding oil"},
     {key:"#TR_ADVISOR_RESIDENCES_DEMANDING_WINE", text:"Residences demanding wine"},
     {key:"#TR_ADVISOR_TOTAL_NUM_HOUSES", text:"Total residences:"},
     {key:"#TR_ADVISOR_AVAILABLE_HOUSING_CAPACITY", text:"Available capacity:"},
     {key:"#TR_ADVISOR_TOTAL_HOUSING_CAPACITY", text:"Total capacity:"},
     {key:"#TR_ADVISOR_ADVISOR_HEADER_HOUSING", text:"Population - Housing"},
     {key:"#TR_ADVISOR_BUTTON_GRAPHS", text:"Graphs"},
     {key:"#TR_ADVISOR_HOUSING_PROSPERITY_RATING", text:"Housing prosperity rating is"},
     {key:"#TR_ADVISOR_PERCENTAGE_IN_MANORS", text:"Percentage of your population in villas and palaces is"},
     {key:"#TR_ADVISOR_PERCENTAGE_IN_SHANTIES", text:"Percentage of your population in tents and shacks is"},
     {key:"#TR_ADVISOR_AVERAGE_TAX", text:"Average tax income per residence is"},
     {key:"#TR_ADVISOR_AVERAGE_AGE", text:"Average age of your population is"},
     {key:"#TR_ADVISOR_PERCENT_IN_WORKFORCE", text:"Percentage of your population in the workforce is"},
     {key:"#TR_ADVISOR_BIRTHS_LAST_YEAR", text:"Births last year:"},
     {key:"#TR_ADVISOR_DEATHS_LAST_YEAR", text:"Deaths last year:"},
     {key:"#TR_ADVISOR_TOTAL_POPULATION", text:"residents total"},

  {key: "#popup_dialog_quit", group:5, id:0 },
  {key: "#popup_dialog_open_trade", group:5, id:2 },
  {key: "#popup_dialog_send_goods", group:5, id:7 },
  {key: "#popup_dialog_not_enough_goods", group:5, id:8 },
  {key: "#popup_dialog_no_legions_available", group:5, id:10 },
  {key: "#popup_dialog_no_legions_selected", group:5, id:12 },
  {key: "#popup_dialog_send_troops", group:5, id:14 },
  {key: "#popup_dialog_delete_fort", group:5, id:16 },
  {key: "#popup_dialog_delete_bridge", group:5, id:20 },
  {key: "#popup_dialog_quit_without_saving", group:5, id:22 },
  {key: "#exit_without_saving", group:5, id:23 },
  {key: "#popup_dialog_no_festival_square", group:5, id:88 },
  {key: "#popup_dialog_delete_dynasty", group:5, id:90 },
  {key: "#popup_dialog_no_dynasty", group:5, id:94 },
  {key: "#replay_mission", group:1, id:2 },
  {key: "#granary_info_title", group:98, id:0 },
  {key: "#granary_no_road_access", group:69, id:25 },
  {key: "#granary_kingdom_supplies_grain", group:98, id:4 },
  {key: "#granary_storing", group:98, id:2 },
  {key: "#granary_space_for", group:98, id:3 },
  {key: "#granary_units", group:8, id:17 },
  {key: "#chief_overseer", group:61, id:0 },
  {key: "#chief_adv_sentiment", group:61, id:1 },
  {key: "#chief_adv_migration", group:61, id:2 },
  {key: "#chief_adv_workers", group:61, id:3 },
  {key: "#chief_adv_foodstocks", group:61, id:4 },
  {key: "#chief_adv_foodconsumption", group:61, id:5 },
  {key: "#chief_adv_health", group:61, id:6 },
  {key: "#chief_adv_religion", group:61, id:7 },
  {key: "#chief_adv_finance", group:61, id:8 },
  {key: "#chief_adv_crime", group:61, id:9 },
  {key: "#chief_adv_military", group:61, id:10 },
  {key: "#chief_adv_kingdom", group:61, id:11 },
  {key: "#chief_adv_nilometr", group:61, id:12 },
  {key: "#trade_overseer", group:54, id:0 },
  {key: "#trade_overseer_hint", group:54, id:1 },
  {key: "#building_have_no_access", group:69, id:25 },
  {key: "#bazaar_info_title", group: 97, id:0},
  {key: "#well_info_title", group:109, id:0},
  {key: "#trade_overseer_prices", group:54, id:30},
  {key: "#trade_overseer_prices_hint", group:68, id:108},
  {key: "#trade_overseer_goto_empire", group:54, id:2},
  {key: "#trade_overseer_goto_empire_hint", group:68, id:42},
  {key: "#festival_square_info_title", group:188, id:0},
  {key: "#visit_rating_advisor", group:105, id:3},
  {key: "#gardens_describe", group:79, id:1},
  {key: "#popup_dialog_proceed", group:43, id:5},

  {key: "#must_build_on_cleared_land", group:19, id:0},
  {key: "#out_of_credit", group:19, id:1},
  {key: "#only_one_building_of_this_type", group:19, id:2},
  {key: "#house_evolution_off", group:19, id:3},
  {key: "#house_evolution_on", group:19, id:4},
  {key: "#road_evolution_off", group:19, id:5},
  {key: "#road_evolution_on", group:19, id:6},
  {key: "#show_people_off", group:19, id:7},
  {key: "#show_people_on", group:19, id:8},
  {key: "#needs_road_access", group:19, id:9},
  {key: "#building_not_next_to_water", group:19, id:10},
  {key: "#not_available_in_this_assignment", group:19, id:11},
  {key: "#not_available_yet", group:19, id:12},
  {key: "#unused_alabaster1", group:19, id:13},
  {key: "#unused_alabaster2", group:19, id:14},
  {key: "#city_needs_more_workers", group:19, id:15},
  {key: "#people_eat_more_than_produce", group:19, id:16},
  {key: "#build_bazaars_to_distribute_food", group:19, id:17},
  {key: "#build_farms_on_meadow", group:19, id:18},
  {key: "#build_clay_pits_close_to_water", group:19, id:19},
  {key: "#build_next_to_rocky_areas", group:19, id:20},
  {key: "#build_wood_cutters_next_to_trees", group:19, id:21},
  {key: "#build_next_to_rocky_areas_ex", group:19, id:22},
  {key: "#scout_along_river_for_site", group:19, id:23},
  {key: "#building_needs_copper_ore", group:19, id:24},
  {key: "#needs_barley", group:19, id:25},
  {key: "#building_needs_flax", group:19, id:26},
  {key: "#building_needs_clay", group:19, id:27},
  {key: "#needs_gems", group:19, id:28},
  {key: "#setup_trade_route_to_import", group:19, id:29},
  {key: "#overseer_of_commerce_to_import", group:19, id:30},
  {key: "#build_copper_mine", group:19, id:31},
  {key: "#build_barley_farm", group:19, id:32},
  {key: "#build_flax_farm", group:19, id:33},
  {key: "#build_clay_pit", group:19, id:34},
  {key: "#build_gem_mine", group:19, id:35},
  {key: "#needs_access_to_water_lift", group:19, id:36},
  {key: "#needs_to_be_next_to_water_to_fill", group:19, id:37},
  {key: "#use_irrigation_ditches", group:19, id:38},
  {key: "#must_be_next_to_wall_for_patrol", group:19, id:39},
  {key: "#needs_recruiter_to_conscript", group:19, id:40},
  {key: "#soldiers_need_supplies_of_weapons", group:19, id:41},
  {key: "#build_juggling_school", group:19, id:42},
  {key: "#build_conservatory", group:19, id:43},
  {key: "#build_dance_school", group:19, id:44},
  {key: "#build_senet_house", group:19, id:45},
  {key: "#unused_demo1", group:19, id:46},
  {key: "#build_towers_on_thick_walls", group:19, id:47},
  {key: "#too_close_to_enemy_troops", group:19, id:48},
  {key: "#company_morale_too_low", group:19, id:49},
  {key: "#army_has_full_complement_of_forts", group:19, id:50},
  {key: "#monthly_autosave_on", group:19, id:51},
  {key: "#monthly_autosave_off", group:19, id:52},
  {key: "#cannot_demolish_bridge_with_people", group:19, id:53},
  {key: "#inland_lake_has_no_sea_access", group:19, id:54},
  {key: "#cannot_set_windows_mode", group:19, id:55},
  {key: "#build_reed_gatherers_near_marsh", group:19, id:56},
  {key: "#shipwrights_need_wood_for_war_vessels", group:19, id:57},
  {key: "#palace_required_for_gold_conversion", group:19, id:58},
  {key: "#cannot_build_over_animal_breeding_grounds", group:19, id:59},
  {key: "#plots_too_far_from_road", group:19, id:60},
  {key: "#city_isolated_from_kingdom_road", group:19, id:61},
  {key: "#restore_access_or_sector_will_stagnate", group:19, id:62},
  {key: "#data_limit_reached", group:19, id:63},
  {key: "#only_build_roadblocks_on_roads", group:19, id:64},
  {key: "#place_other_ferry_landing", group:19, id:65},
  {key: "#no_valid_spot_for_ferry_landing", group:19, id:66},
  {key: "#maximum_food_types_reached", group:19, id:67},
  {key: "#cannot_add_meat_without_straw", group:19, id:68},
  {key: "#cannot_produce_meat_in_city", group:19, id:69},
  {key: "#only_one_special_rock_type", group:19, id:70},
  {key: "#must_build_temple_complex_first", group:19, id:71},
  {key: "#temple_complex_limits", group:19, id:72},
  {key: "#oracle_altar_placement", group:19, id:73},
  {key: "#needs_groundwater", group:19, id:74},
  {key: "#entertainment_venue_at_intersection", group:19, id:75},
  {key: "#must_have_completed_temple_first", group:19, id:76},
  {key: "#need_500_papyrus_for_library", group:19, id:77},
  {key: "#building_needs_reeds", group:19, id:78},
  {key: "#build_reed_gatherer", group:19, id:79},
  {key: "#building_needs_straw", group:19, id:80},
  {key: "#build_grain_farm", group:19, id:81},
  {key: "#full_complement_of_warship_wharves", group:19, id:82},
  {key: "#need_100_blocks_of_granite_for_obelisk", group:19, id:83},
  {key: "#need_200_blocks_of_granite_for_large_obelisk", group:19, id:84},
  {key: "#monuments_removed", group:19, id:85},
  {key: "#only_one_obelisk_at_a_time", group:19, id:86},
  {key: "#no_taxes_without_palace", group:19, id:87},
  {key: "#need_220_blocks_of_sandstone_for_sun_temple", group:19, id:88},
  {key: "#only_one_sun_temple_at_a_time", group:19, id:89},
  {key: "#too_few_jobs_for_population", group:19, id:90},
  {key: "#low_food_levels", group:19, id:91},
  {key: "#people_eating_more_than_produced", group:19, id:92},
  {key: "#city_health_appalling_plague_imminent", group:19, id:93},
  {key: "#city_health_terrible_plague_likely", group:19, id:94},
  {key: "#city_health_worsening_serious_risk", group:19, id:95},
  {key: "#city_health_getting_worse_plague_could_strike", group:19, id:96},
  {key: "#plague_likely_health_improving", group:19, id:97},
  {key: "#risk_of_plague_but_improving", group:19, id:98},
  {key: "#health_improving_plague_still_possible", group:19, id:99},
  {key: "#palace_robbed", group:19, id:100},
  {key: "#thief_stole_savings", group:19, id:101},
  {key: "#no_troops_for_defense", group:19, id:102},
  {key: "#loathed_in_city", group:19, id:103},
  {key: "#people_very_angry", group:19, id:104},
  {key: "#people_angry", group:19, id:105},
  {key: "#people_very_upset", group:19, id:106},
  {key: "#people_upset", group:19, id:107},
  {key: "#people_annoyed", group:19, id:108},
  {key: "#people_indifferent", group:19, id:109},
  {key: "#people_pleased", group:19, id:110},
  {key: "#people_very_pleased", group:19, id:111},
  {key: "#people_extremely_pleased", group:19, id:112},
  {key: "#people_love_you", group:19, id:113},
  {key: "#people_idolize_you", group:19, id:114},
  {key: "#unhappiness_lack_of_food", group:19, id:115},
  {key: "#unhappiness_lack_of_jobs", group:19, id:116},
  {key: "#unhappiness_high_taxes", group:19, id:117},
  {key: "#unhappiness_low_wages", group:19, id:118},
  {key: "#unhappiness_too_many_slums", group:19, id:119},
  {key: "#immigration_people_coming", group:19, id:120},
  {key: "#immigration_no_housing", group:19, id:121},
  {key: "#immigration_low_wages_deter", group:19, id:122},
  {key: "#immigration_lack_of_jobs", group:19, id:123},
  {key: "#immigration_lack_of_food", group:19, id:124},
  {key: "#immigration_high_taxes", group:19, id:125},
  {key: "#immigration_slums_deter", group:19, id:126},
  {key: "#immigration_low_sentiment", group:19, id:127},
  {key: "#emigration_no_housing", group:19, id:128},
  {key: "#emigration_low_wages", group:19, id:129},
  {key: "#emigration_high_unemployment", group:19, id:130},
  {key: "#emigration_lack_of_food", group:19, id:131},
  {key: "#emigration_high_taxes", group:19, id:132},
  {key: "#emigration_slums_encourage_leaving", group:19, id:133},
  {key: "#emigration_low_sentiment", group:19, id:134},
  {key: "#building_needs_beer", group:19, id:135},
  {key: "#build_brewery", group:19, id:136},
  {key: "#needs_papyrus", group:19, id:137},
  {key: "#build_papyrus_maker", group:19, id:138},
  {key: "#building_needs_linen", group:19, id:139},
  {key: "#build_weaver", group:19, id:140},
  {key: "#building_needs_wood", group:19, id:141},
  {key: "#build_wood_cutter", group:19, id:142},
  {key: "#building_needs_clay_and_straw", group:19, id:143},
  {key: "#import_clay_trade_route", group:19, id:144},
  {key: "#import_clay_overseer", group:19, id:145},
  {key: "#import_straw_trade_route", group:19, id:146},
  {key: "#import_straw_overseer", group:19, id:147},
  {key: "#monument_needs_stone_and_limestone", group:19, id:148},
  {key: "#build_stone_quarry", group:19, id:149},
  {key: "#import_stone_trade_route", group:19, id:150},
  {key: "#import_stone_overseer", group:19, id:151},
  {key: "#build_limestone_quarry", group:19, id:152},
  {key: "#import_limestone_trade_route", group:19, id:153},
  {key: "#import_limestone_overseer", group:19, id:154},
  {key: "#monument_needs_plain_stone", group:19, id:155},
  {key: "#monument_needs_limestone", group:19, id:156},
  {key: "#monument_needs_bricks_and_limestone", group:19, id:157},
  {key: "#build_brickworks", group:19, id:158},
  {key: "#import_bricks_trade_route", group:19, id:159},
  {key: "#import_bricks_overseer", group:19, id:160},
  {key: "#monument_needs_bricks", group:19, id:161},
  {key: "#monument_needs_sandstone", group:19, id:162},
  {key: "#build_sandstone_quarry", group:19, id:163},
  {key: "#import_beer_overseer", group:19, id:164},
  {key: "#import_beer_trade_route", group:19, id:165},
  {key: "#import_barley_overseer", group:19, id:166},
  {key: "#import_barley_trade_route", group:19, id:167},
  {key: "#import_reeds_overseer", group:19, id:168},
  {key: "#import_reeds_trade_route", group:19, id:169},
  {key: "#import_papyrus_overseer", group:19, id:170},
  {key: "#import_papyrus_trade_route", group:19, id:171},
  {key: "#import_flax_overseer", group:19, id:172},
  {key: "#import_flax_trade_route", group:19, id:173},
  {key: "#import_linen_overseer", group:19, id:174},
  {key: "#import_linen_trade_route", group:19, id:175},
  {key: "#building_removed_mortuaries", group:19, id:176},
  {key: "#building_removed_senet_house", group:19, id:177},
  {key: "#building_removed_scribal_schools", group:19, id:178},
  {key: "#building_removed_libraries", group:19, id:179},
  {key: "#building_removed_weaponsmiths", group:19, id:180},
  {key: "#building_removed_chariot_maker", group:19, id:181},
  {key: "#building_removed_fort_infantry", group:19, id:182},
  {key: "#building_removed_fort_archers", group:19, id:183},
  {key: "#building_removed_fort_charioteers", group:19, id:184},
  {key: "#building_removed_academies", group:19, id:185},
  {key: "#mausoleum_needs_sandstone", group:19, id:186},
  {key: "#build_brewery_or_import_beer", group:19, id:187},
  {key: "#build_papyrus_maker_or_import", group:19, id:188},
  {key: "#build_weaver_or_import_linen", group:19, id:189},
  {key: "#tax_collector_robbed", group:19, id:190},
  {key: "#courthouse_robbed", group:19, id:191},
  {key: "#mansion_destroyed", group:19, id:192},
  {key: "#palace_destroyed", group:19, id:193},
  {key: "#tax_collector_destroyed", group:19, id:194},
  {key: "#courthouse_destroyed", group:19, id:195},
  {key: "#gold_miner_robbed", group:19, id:196},
  {key: "#build_granary", group:19, id:197},
  {key: "#build_granaries", group:19, id:198},
  {key: "#max_docks_reached", group:19, id:199},
  {key: "#shrines_near_road_required", group:19, id:200},
  {key: "#build_jugglers_school", group:19, id:201},
  {key: "#build_conservatory", group:19, id:202},
  {key: "#build_dance_school", group:19, id:203},
  {key: "#company_cannot_reach_destination", group:19, id:204},
  {key: "#game_saved", group:19, id:205},
  {key: "#must_be_on_clear_land", group:19, id:206},
  {key: "#causeway_needs_water", group:19, id:207},
  {key: "#festival_square_on_intersection", group:19, id:208},
  {key: "#no_immigration_with_enemies", group:19, id:209},
  {key: "#cheats_enabled", group:19, id:210},
  {key: "#cheats_disabled", group:19, id:211},
  {key: "#flood_perfect", group:19, id:212},
  {key: "#flood_excellent", group:19, id:213},
  {key: "#flood_good", group:19, id:214},
  {key: "#flood_mediocre", group:19, id:215},
  {key: "#flood_poor", group:19, id:216},
  {key: "#flood_failed", group:19, id:217},
  {key: "#price_increase", group:19, id:218},
  {key: "#price_decrease", group:19, id:219},
  {key: "#wages_lowered", group:19, id:220},
  {key: "#wages_raised", group:19, id:221},
  {key: "#trade_decreases", group:19, id:222},
  {key: "#trade_increases", group:19, id:223},
  {key: "#kingdom_standing_rises", group:19, id:224},
  {key: "#population_milestone", group:19, id:225},
  {key: "#minor_god_blessing", group:19, id:226},
  {key: "#festival_starting", group:19, id:227},
  {key: "#goods_auto_dispatched", group:19, id:228},
  {key: "#building_removed_zoo", group:19, id:229},
  {key: "#building_needs_game_meat", group:19, id:230},
  {key: "#build_hunting_lodge", group:19, id:231},
  {key: "#build_hunting_lodge_or_import", group:19, id:232},
  {key: "#monument_needs_copper", group:19, id:233},
  {key: "#monument_needs_marble", group:19, id:234},
  {key: "#one_library_only", group:19, id:235},
  {key: "#one_pharos_only", group:19, id:236},
  {key: "#one_caesareum_only", group:19, id:237},
  {key: "#disease_strikes", group:19, id:238},
  {key: "#malaria_strikes", group:19, id:239},
  {key: "#monument_needs_granite", group:19, id:240},
  {key: "#must_be_over_rocks", group:19, id:241},
  {key: "#pharos_not_demolishable", group:19, id:242},
  {key: "#tomb_robbers_plundered", group:19, id:243},
  {key: "#mausoleum_plundered", group:19, id:244},
  {key: "#tomb_robbers_stole_provisions", group:19, id:245},
  {key: "#tomb_robber_caught", group:19, id:246},
  {key: "#building_needs_oil_and_pottery", group:19, id:247},
  {key: "#build_potter", group:19, id:248},
  {key: "#import_pottery_trade_route", group:19, id:249},
  {key: "#import_pottery_overseer", group:19, id:250},
  {key: "#import_oil_trade_route", group:19, id:251},
  {key: "#import_oil_overseer", group:19, id:252},
  {key: "#building_needs_henna", group:19, id:253},
  {key: "#build_henna_farm", group:19, id:254},
  {key: "#import_henna_trade_route", group:19, id:255},
  {key: "#import_henna_overseer", group:19, id:256},
  {key: "#building_needs_oil", group:19, id:257},
  {key: "#building_needs_pottery", group:19, id:258},
  {key: "#build_paint_maker_or_import", group:19, id:259},
  {key: "#build_paint_maker", group:19, id:260},
  {key: "#building_needs_clay_and_paint", group:19, id:261},
  {key: "#employees_needed", group:19, id:262},
  {key: "#must_be_over_cliffs", group:19, id:263},
  {key: "#entrance_on_clear_land", group:19, id:264},
  {key: "#warning_shipwright_needed", group:19, id:316},

  {key: "#house_low_desirabilty", group:127, id:40},
  {key: "#lacks_access_primitive_water", group:127, id:41},
  {key: "#not_visited_by_water_carrier", group:127, id:42},
  {key: "#no_entertainment_to_be_found", group:127, id:43},
  {key: "#any_entertainment_in_location", group:127, id:44},
  {key: "#too_little_entertainment_in_location", group:127, id:45},
  {key: "#some_entertainment_found_location", group:127, id:46},
  {key: "#good_entertainment_found_location", group:127, id:47},
  {key: "#excellent_entertainment_found_location", group:127, id:48},
  {key: "#one_food_type_need", group:127, id:49},
  {key: "#two_food_types_need", group:127, id:50},
  {key: "#three_food_types_need", group:127, id:51},
  {key: "#no_bazaar_access", group:127, id:52},
  {key: "#low_bazaar_access", group:127, id:53},
  {key: "#lost_basic_educational_facilities ", group:127, id:54},
  {key: "#lost_access_to_library ", group:127, id:55},
  {key: "#lost_access_to_scribal_school ", group:127, id:56},
  {key: "#lost_access_to_higher_education ", group:127, id:57},
  {key: "#no_access_to_magistrates", group:127, id:58},
  {key: "#run_out_of_pottery", group:127, id:59},
  {key: "#lost_all_access_to_local_religious", group:127, id:60},
  {key: "#access_to_one_local_religious", group:127, id:61},
  {key: "#access_to_two_local_religious", group:127, id:62},
  {key: "#lost_dentist_access", group:127, id:63},
  {key: "#no_access_to_physician", group:127, id:64},
  {key: "#no_access_to_mortuary", group:127, id:65},
  {key: "#hard_access_to_physician", group:127, id:66},
  {key: "#run_out_of_linen", group:127, id:67},
  {key: "#run_out_of_beer", group:127, id:69},
  {key: "#cannot_evolve_cause_low_desirability", group:127, id:70},
  {key: "#cannot_evolve_most_primitive_water_source", group:127, id:71},
  {key: "#cannot_evolve_access_to_water_carrier", group:127, id:72},
  {key: "#cannot_evolve_no_entertainment", group:127, id:73},
  {key: "#cannot_evolve_hardly_any_entertainment", group:127, id:74},
  {key: "#cannot_evolve_too_little_entertainment", group:127, id:75},
  {key: "#cannot_evolve_some_entertainment", group:127, id:76},
  {key: "#cannot_evolve_good_entertainment", group:127, id:77},
  {key: "#cannot_evolve_excellent_entertainment", group:127, id:78},
  {key: "#cannot_evolve_needs_supply_food", group:127, id:79},
  {key: "#cannot_evolve_needs_second_type_food", group:127, id:80},
  {key: "#cannot_evolve_needs_third_type_food", group:127, id:81},
  {key: "#cannot_evolve_needs_access_bazaar", group:127, id:82},
  {key: "#cannot_evolve_needs_low_access_bazaar", group:127, id:83},
  {key: "#cannot_evolve_needs_basic_education", group:127, id:84},
  {key: "#cannot_evolve_needs_library_education", group:127, id:85},
  {key: "#cannot_evolve_needs_school_education", group:127, id:86},
  {key: "#cannot_evolve_needs_academy_education", group:127, id:87},
  {key: "#cannot_evolve_needs_magistrate", group:127, id:88},
  {key: "#cannot_evolve_needs_pottery", group:127, id:89},
  {key: "#cannot_evolve_needs_religious", group:127, id:90},
  {key: "#cannot_evolve_needs_religious_two_gods", group:127, id:91},
  {key: "#cannot_evolve_needs_religious_three_gods", group:127, id:92},
  {key: "#cannot_evolve_needs_dentist", group:127, id:93},
  {key: "#cannot_evolve_needs_physician", group:127, id:94},
  {key: "#cannot_evolve_needs_mortuary_has_physician", group:127, id:95},
  {key: "#cannot_evolve_needs_physician_mortuary_has", group:127, id:96},
  {key: "#cannot_evolve_needs_linen", group:127, id:97},
  {key: "#cannot_evolve_needs_beer", group:127, id:99},
  {key: "#cannot_evolve_needs_jewlery", group:127, id:108},

  {key: "#dwellers_palace_are_pinnacle", group:127, id:100},
  {key: "#house_upgrade_inprogress", group:127, id:101},
  {key: "#house_nearby_building", group:127, id:102},
  {key: "#having_detrimental_effect", group:127, id:103},
  {key: "#house_upgrade_nospace", group:127, id:104},
  {key: "#TR_CONFIG_HEADER_LANGUAGES", lang:"en", text: "Game language"},

  {key: "#hunter_ostrich_good_city", lang:"en", text: "I like it here, but there is always room for improvement."},
]
