 log_info("akhenaten: localization_po config started")

localization_po = [
 { key:"#TR_NO_PATCH_TITLE", text:""},
 { key:"#TR_NO_PATCH_MESSAGE", text:""},
 { key:"#TR_MISSING_FONTS_TITLE", text:"Brakuje czcionek"},
 { key:"#TR_MISSING_FONTS_MESSAGE", text:"" },
 { key:"#TR_NO_EDITOR_TITLE", text:"Edytor nie jest zainstalowany"},
 { key:"#TR_NO_EDITOR_MESSAGE", text:"" },
 { key:"#TR_INVALID_LANGUAGE_TITLE", text:"Nieprawidłowy folder językowy"},
 { key:"#TR_INVALID_LANGUAGE_MESSAGE", text:""},
 { key:"#TR_BUTTON_OK", text:"OK"},
 { key:"#TR_BUTTON_CANCEL", text:"Anuluj"},
 { key:"#TR_BUTTON_RESET_DEFAULTS", text:"Ustaw domyślne"},
 { key:"#TR_BUTTON_CONFIGURE_HOTKEYS", text:"Skróty klawiszowe"},
 { key:"#TR_CONFIG_TITLE", text:"konfiguracja"},
 { key:"#TR_CONFIG_LANGUAGE_LABEL", text:"Język:"},
 { key:"#TR_CONFIG_LANGUAGE_DEFAULT", text:"(domyślny)"},
 { key:"#TR_CONFIG_HEADER_UI_CHANGES", text:"Zmiany interfejsu użytkownika"},
 { key:"#TR_CONFIG_HEADER_GAMEPLAY_CHANGES", text:"Zmiany gry"},
 { key:"#TR_CONFIG_HEADER_GODS_CHANGES", text:"Gods changes"},
 { key:"#TR_CONFIG_HEADER_BUILDING_CHANGES", text:"Building changes"},
 { key:"#TR_CONFIG_HEADER_RESOURCE_CHANGES", text:"Resource changes"},
 { key:"#TR_CONFIG_SHOW_INTRO_VIDEO", text:"Odgrywaj film wprowadzający"},
 { key:"#TR_CONFIG_SIDEBAR_INFO", text:"Dodatkowe informacje w panelu sterowania"},
 { key:"#TR_CONFIG_SMOOTH_SCROLLING", text:"Płynne przewijanie"},
 { key:"#TR_CONFIG_VISUAL_FEEDBACK_ON_DELETE", text:"Pokaż wybrany obszar przy oczyszczaniu terenu"},
 { key:"#TR_CONFIG_ALLOW_CYCLING_TEMPLES", text:"Pozwól na budowę kolejno każdej ze świątyń"},
 { key:"#TR_CONFIG_SHOW_WATER_STRUCTURE_RANGE", text:"Pokaż zasięg przy budowie rezerwuarów, fontann i studni"},
 { key:"#TR_CONFIG_SHOW_CONSTRUCTION_SIZE", text:"Pokaż rozmiar budowy przy przeciąganiu kursorem"},
 { key:"#TR_CONFIG_HIGHLIGHT_LEGIONS", text:"Podświetl legion przy najechaniu kursorem"},
 { key:"#TR_CONFIG_FIX_IMMIGRATION_BUG", text:"Napraw błąd z imigrację na najwyższym poziomie trudności"},
 { key:"#TR_CONFIG_FIX_100_YEAR_GHOSTS", text:"Napraw 100-letnie duchy"},
 { key:"#TR_CONFIG_FIX_EDITOR_EVENTS", text:"Napraw zmianę imperatora i czas przetrwania w konstruktorze miast"},
 { key:"#TR_HOTKEY_TITLE", text:"Konfiguracja skrótów klawiszowych"},
 { key:"#TR_HOTKEY_LABEL", text:"Skrót klawiszowy"},
 { key:"#TR_HOTKEY_ALTERNATIVE_LABEL", text:"Alternatywny"},
 { key:"#TR_HOTKEY_HEADER_ARROWS", text:"Strzałki kierunkowe"},
 { key:"#TR_HOTKEY_HEADER_GLOBAL", text:"Globalne skróty klawiszowe"},
 { key:"#TR_HOTKEY_HEADER_CITY", text:"Miejskie skróty klawiszowe"},
 { key:"#TR_HOTKEY_HEADER_ADVISORS", text:"Doradcy"},
 { key:"#TR_HOTKEY_HEADER_OVERLAYS", text:"Widoki"},
 { key:"#TR_HOTKEY_HEADER_BOOKMARKS", text:"Miejskie miejsca skoku"},
 { key:"#TR_HOTKEY_HEADER_EDITOR", text:"Edytor"},
 { key:"#TR_HOTKEY_ARROW_UP", text:"Góra"},
 { key:"#TR_HOTKEY_ARROW_DOWN", text:"Dół"},
 { key:"#TR_HOTKEY_ARROW_LEFT", text:"Lewo"},
 { key:"#TR_HOTKEY_ARROW_RIGHT", text:"Prawo"},
 { key:"#TR_HOTKEY_TOGGLE_FULLSCREEN", text:"Przełącz pełny ekran"},
 { key:"#TR_HOTKEY_CENTER_WINDOW", text:"Wycentruj okno"},
 { key:"#TR_HOTKEY_RESIZE_TO_640", text:"Zmień rozmiar okna do 640x480"},
 { key:"#TR_HOTKEY_RESIZE_TO_800", text:"Zmień rozmiar okna do 800x600"},
 { key:"#TR_HOTKEY_RESIZE_TO_1024", text:"Zmień rozmiar okna do 1024x768"},
 { key:"#TR_HOTKEY_SAVE_SCREENSHOT", text:"Zapisz zrzut ekranu"},
 { key:"#TR_HOTKEY_SAVE_CITY_SCREENSHOT", text:"Zapisz zrzut ekranu miasta"},
 { key:"#TR_HOTKEY_LOAD_FILE", text:"Wczytaj plik"},
 { key:"#TR_HOTKEY_SAVE_FILE", text:"Zapisz plik"},
 { key:"#TR_HOTKEY_INCREASE_GAME_SPEED", text:"Zwiększ prędkość gry"},
 { key:"#TR_HOTKEY_DECREASE_GAME_SPEED", text:"Zmniejsz prędkość gry"},
 { key:"#TR_HOTKEY_TOGGLE_PAUSE", text:"Pauza"},
 { key:"#TR_HOTKEY_CYCLE_LEGION", text:"Przełącz między legionami"},
 { key:"#TR_HOTKEY_ROTATE_MAP_LEFT", text:"Obróć mapę w lewo"},
 { key:"#TR_HOTKEY_ROTATE_MAP_RIGHT", text:"Obróć mapę w prawo"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_LABOR", text:"Doradca zatrudnienia"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_MILITARY", text:"Doradca legionów"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_IMPERIAL", text:"Doradca imperialny"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_RATINGS", text:"Doradca wyników"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_TRADE", text:"Doradca handlowy"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_POPULATION", text:"Doradca populacji"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_HEALTH", text:"Doradca zdrowia"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_EDUCATION", text:"Doradca edukacji"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_ENTERTAINMENT", text:"Doradca rozrywki"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_RELIGION", text:"Doradca religijny"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_FINANCIAL", text:"Doradca finansowy"},
 { key:"#TR_HOTKEY_SHOW_ADVISOR_CHIEF", text:"Główny doradca"},
 { key:"#TR_HOTKEY_TOGGLE_OVERLAY", text:"Przełącz między widokami"},
 { key:"#TR_HOTKEY_SHOW_OVERLAY_WATER", text:"Pokaż widok wody"},
 { key:"#TR_HOTKEY_SHOW_OVERLAY_FIRE", text:"Pokaż widok pożarów"},
 { key:"#TR_HOTKEY_SHOW_OVERLAY_DAMAGE", text:"Pokaż widok zniszczenia"},
 { key:"#TR_HOTKEY_SHOW_OVERLAY_CRIME", text:"Pokaż widok zbrodni"},
 { key:"#TR_HOTKEY_SHOW_OVERLAY_PROBLEMS", text:"Pokaż widok problemów"},
 { key:"#TR_HOTKEY_GO_TO_BOOKMARK_1", text:"Przejdź do punktu skoku 1"},
 { key:"#TR_HOTKEY_GO_TO_BOOKMARK_2", text:"Przejdź do punktu skoku 2"},
 { key:"#TR_HOTKEY_GO_TO_BOOKMARK_3", text:"Przejdź do punktu skoku 3"},
 { key:"#TR_HOTKEY_GO_TO_BOOKMARK_4", text:"Przejdź do punktu skoku 4"},
 { key:"#TR_HOTKEY_SET_BOOKMARK_1", text:"Ustaw punkt skoku 1"},
 { key:"#TR_HOTKEY_SET_BOOKMARK_2", text:"Ustaw punkt skoku 2"},
 { key:"#TR_HOTKEY_SET_BOOKMARK_3", text:"Ustaw punkt skoku 3"},
 { key:"#TR_HOTKEY_SET_BOOKMARK_4", text:"Ustaw punkt skoku 4"},
 { key:"#TR_HOTKEY_EDITOR_TOGGLE_BATTLE_INFO", text:"Przełącz informacje o bitwach"},
 { key:"#TR_HOTKEY_EDIT_TITLE", text:"Wprowadź skrót"},
 { key:"#TR_BUILDING_ROADBLOCK", text:"Blokada drogi"},
 { key:"#TR_BUILDING_ROADBLOCK_DESC", text:"Blokada drogi zatrzymuje przechodniów bez celu."},
 { key:"#TR_HEADER_HOUSING", text:"Domy"},
 { key:"#TR_ADVISOR_HOUSING_ROOM", text:"W miejskich domach jest miejsce dla"},
 { key:"#TR_ADVISOR_HOUSING_NO_ROOM", text:"Brak miejsca w miejskich domach."},
 { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_POTTERY", text:"Domy wymagające garnków"},
 { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_FURNITURE", text:"Domy wymagające mebli"},
 { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_OIL", text:"Domy wymagające oliwy"},
 { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_WINE", text:"Domy wymagające wina"},
 { key:"#TR_ADVISOR_TOTAL_NUM_HOUSES", text:"Razem domów:"},
 { key:"#TR_ADVISOR_AVAILABLE_HOUSING_CAPACITY", text:"Dostępne zakwaterowanie:"},
 { key:"#TR_ADVISOR_TOTAL_HOUSING_CAPACITY", text:"Całkowite zakwaterowanie:"},
 { key:"#TR_ADVISOR_ADVISOR_HEADER_HOUSING", text:"Populacja - domy"},
 { key:"#TR_ADVISOR_BUTTON_GRAPHS", text:"Wykresy"},
 { key:"#TR_ADVISOR_HOUSING_PROSPERITY_RATING", text:"Bogactwo domów"},
 { key:"#TR_ADVISOR_PERCENTAGE_IN_MANORS", text:"Procent populacji w willach i pałacach"},
 { key:"#TR_ADVISOR_PERCENTAGE_IN_SHANTIES", text:"Procent populacji w namiotach i szałasach"},
 { key:"#TR_ADVISOR_AVERAGE_TAX", text:"Średni podatek na głowę"},
 { key:"#TR_ADVISOR_AVERAGE_AGE", text:"Średnia wieku populacji"},
 { key:"#TR_ADVISOR_PERCENT_IN_WORKFORCE", text:"Procent populacji w sile roboczej"},
 { key:"#TR_ADVISOR_BIRTHS_LAST_YEAR", text:"Narodzin w zeszłym roku:"},
 { key:"#TR_ADVISOR_DEATHS_LAST_YEAR", text:"Śmierci w zeszłym roku:"},
 { key:"#TR_ADVISOR_TOTAL_POPULATION", text:"Razem mieszkańców"}
]