log_info("akhenaten: localization_de config started")

localization_de = [
     { key:"#TR_NO_PATCH_TITLE", text:"Patch ???"},
     { key:"#TR_NO_PATCH_MESSAGE", text:"" },
     { key:"#TR_MISSING_FONTS_TITLE", text:"Schriftarten fehlen"},
     { key:"#TR_MISSING_FONTS_MESSAGE", text:""},
     { key:"#TR_NO_EDITOR_TITLE", text:"Editor nicht installiert"},
     { key:"#TR_NO_EDITOR_MESSAGE", text:""},
     { key:"#TR_INVALID_LANGUAGE_TITLE", text:"Ungültiges Sprachverzeichnis"},
     { key:"#TR_INVALID_LANGUAGE_MESSAGE", text:"Das gewählte Verzeichnis enthält kein gültiges Sprachpaket. Bitte überprüfe das Protokoll auf Fehler."},
     { key:"#TR_BUTTON_OK", text:"OK"},
     { key:"#TR_BUTTON_CANCEL", text:"Abbrechen"},
     { key:"#TR_BUTTON_RESET_DEFAULTS", text:"Zurücksetzen"},
     { key:"#TR_BUTTON_CONFIGURE_HOTKEYS", text:"Tastenkombinationen"},
     { key:"#TR_BUTTON_NEXT", text:"+"},
     { key:"#TR_BUTTON_PREV", text:"-"},
     { key:"#TR_CONFIG_TITLE", text:"Akhenaten Einstellungen"},
     { key:"#TR_CONFIG_LANGUAGE_LABEL", text:"Sprache:"},
     { key:"#TR_CONFIG_LANGUAGE_DEFAULT", text:"(Standard)"},
     { key:"#TR_CONFIG_PAGE_LABEL", text:"Seite"},
     { key:"#TR_CONFIG_HEADER_UI_CHANGES", text:"Benutzeroberfläche ändern"},
     { key:"#TR_CONFIG_HEADER_GAMEPLAY_CHANGES", text:"Spielablauf ändern"},
     { key:"#TR_CONFIG_HEADER_GODS_CHANGES", text:"Götter ändern"},
     { key:"#TR_CONFIG_HEADER_BUILDING_CHANGES", text:"Gebäude ändern"},
     { key:"#TR_CONFIG_HEADER_RESOURCE_CHANGES", text:"Resourcen ändern"},
     { key:"#TR_CONFIG_SHOW_INTRO_VIDEO", text:"Intro-Videos abspielen"},
     { key:"#TR_CONFIG_HIDE_NEW_GAME_TOP_MENU", text:"Button 'Neues Spiel' im oberen Menü ausblenden"},
     { key:"#TR_CONFIG_SAVE_YEAR_KINGDOME_RATING", text:"Königreichswertung beim jährlichen Update speichern"},
     { key:"#TR_CONFIG_SIDEBAR_INFO", text:"Aktiviere zusätzliche Informationen im rechtsseitigen Bedienfeld"},
     { key:"#TR_CONFIG_SMOOTH_SCROLLING", text:"Aktiviere sanftes Scrollen"},
     { key:"#TR_CONFIG_VISUAL_FEEDBACK_ON_DELETE", text:"Beim Planieren der Landfläche das visuelle Feedback verbessern"},
     { key:"#TR_CONFIG_ALLOW_CYCLING_TEMPLES", text:"Erlaube alle Tempel nacheinander zu bauen"},
     { key:"#TR_CONFIG_SHOW_WATER_STRUCTURE_RANGE", text:"Zeige Reichweite beim Bauen von Reservoirs und Brunnen"},
     { key:"#TR_CONFIG_SHOW_CONSTRUCTION_SIZE", text:"Zeige Konstruktionsgröße beim Bauen"},
     { key:"#TR_CONFIG_HIGHLIGHT_LEGIONS", text:"Hebe Legion beim Berühren mit der Maus hervor"},
     { key:"#TR_CONFIG_ROTATE_MANUALLY", text:"Torhaus und Triumphbogen per Hotkey drehen"},
     { key:"#TR_CONFIG_FIX_IMMIGRATION_BUG", text:"Behebe Immigrationsfehler auf 'Sehr schwierig'"},
     { key:"#TR_CONFIG_FIX_100_YEAR_GHOSTS", text:"Behebe '100 Jahre alte Geister'"},
     { key:"#TR_CONFIG_FIX_EDITOR_EVENTS", text:"Behebe Wechsel- und Überlebenszeit des Imperators in eigenen Missionen"},
     { key:"#TR_CONFIG_DRAW_WALKER_WAYPOINTS", text:"Wegpunkte von Läufern nach Rechtsklick auf Gebäude anzeigen"},
     { key:"#TR_CONFIG_ZOOM_STEPPED", text:"Zoom aktivieren (kann langsam sein, verbraucht mehr RAM)"},
     { key:"#TR_CONFIG_COMPLETE_RATING_COLUMNS", text:"Unvollständige Bewertungs-Spalten bei niedrigen Zielen beheben"},
     { key:"#TR_CONFIG_GRANDFESTIVAL", text:"Große Feste erlauben zusätzlichen Segen eines Gottes"},
     { key:"#TR_CONFIG_JEALOUS_GODS", text:"Eifersucht der Götter deaktivieren"},
     { key:"#TR_CONFIG_GLOBAL_LABOUR", text:"Globalen Arbeitskräftepool aktivieren"},
     { key:"#TR_CONFIG_SCHOOL_WALKERS", text:"Reichweite von Schulbesuchern erweitern"},
     { key:"#TR_CONFIG_RETIRE_AT_60", text:"Rentenalter der Bürger von 50 auf 60 erhöhen"},
     { key:"#TR_CONFIG_FIXED_WORKERS", text:"Fester Arbeiterpool – 38 % der Bevölkerung"},
     { key:"#TR_CONFIG_EXTRA_FORTS", text:"Bau von 4 zusätzlichen Forts erlauben"},
     { key:"#TR_CONFIG_WOLVES_BLOCK", text:"Bau in der Nähe von Wölfen blockieren"},
     { key:"#TR_CONFIG_DYNAMIC_GRANARIES", text:"Straßenblockierung bei nicht verbundenen Speichern"},
     { key:"#TR_CONFIG_MORE_STOCKPILE", text:"Haushalte lagern mehr Waren vom Markt ein"},
     { key:"#TR_CONFIG_NO_BUYER_DISTRIBUTION", text:"Marktfrauen verteilen keine gekauften Waren"},
     { key:"#TR_CONFIG_IMMEDIATELY_DELETE_BUILDINGS", text:"Gebäude sofort zerstören"},
     { key:"#TR_CONFIG_GETTING_GRANARIES_GO_OFFROAD", text:"Transportkarren aus Speichern dürfen Offroad fahren"},
     { key:"#TR_CONFIG_GRANARIES_GET_DOUBLE", text:"Doppelte Kapazität für Speicher-Transportkarren"},
     { key:"#TR_CONFIG_TOWER_SENTRIES_GO_OFFROAD", text:"Wachtürme benötigen keine Straßenverbindung zur Kaserne"},
     { key:"#TR_CONFIG_FARMS_DELIVER_CLOSE", text:"Farmen und Werften beliefern nur nahegelegene Speicher"},
     { key:"#TR_CONFIG_DELIVER_ONLY_TO_ACCEPTING_GRANARIES", text:"Nahrung wird nicht an abholende Speicher geliefert"},
     { key:"#TR_CONFIG_ALL_HOUSES_MERGE", text:"Alle Häuser verschmelzen"},
     { key:"#TR_CONFIG_WINE_COUNTS_IF_OPEN_TRADE_ROUTE", text:"Offene Handelsroute zählt als andere Weinsorte"},
     { key:"#TR_CONFIG_RANDOM_COLLAPSES_TAKE_MONEY", text:"Zufällige Einstürze von Lehm- und Eisenminen kosten Geld"},
     { key:"#TR_CONFIG_MULTIPLE_BARRACKS", text:"Bau mehrerer Kasernen erlauben"},
     { key:"#TR_CONFIG_NOT_ACCEPTING_WAREHOUSES", text:"Lagerhäuser akzeptieren beim Bau nichts"},
     { key:"#TR_CONFIG_HOUSES_DONT_EXPAND_INTO_GARDENS", text:"Häuser dehnen sich nicht in Gärten aus"},
     { key:"#TR_CONFIG_FIX_IRRIGATION_RANGE", text:"Reichweite der Bewässerung korrigieren"},
     { key:"#TR_CONFIG_FIX_FARM_PRODUCING", text:"Fehler bei der Farmproduktion beheben"},
     { key:"#TR_CONFIG_CAMERA_KEEP_INERTIA", text:"Kamera behält Trägheit bei"},
     { key:"#TR_CONFIG_UNDERSTAFFED_ACCEPT_GOODS", text:"Unterbesetzte Gebäude nehmen trotzdem Waren an"},
     { key:"#TR_CONFIG_MULTIPLE_TEMPLE_COMPLEXES", text:"Mehrere Tempelkomplexe erlauben"},
     { key:"#TR_CONFIG_MULTIPLE_MONUMENTS", text:"Mehrere Monumente erlauben"},
     { key:"#TR_CONFIG_SOIL_DEPLETION", text:"Bodenauslaugung"},
     { key:"#TR_CONFIG_MULTIPLE_GATHERERS", text:"Mehrere Sammler"},
     { key:"#TR_CONFIG_FIREMAN_RETURNING", text:"Feuerwehrmann kehrt nach Brandbekämpfung zurück"},
     { key:"#TR_CONFIG_CART_SPEED_DEPENDS_QUANTITY", text:"Karrengeschwindigkeit hängt von Warenmenge ab"},
     { key:"#TR_CONFIG_CH_CITIZEN_ROAD_OFFSET", text:"Versatz von Bürgern auf Straßen verwenden"},
     { key:"#TR_CONFIG_CH_WORK_CAMP_ONE_WORKER_PER_MONTH", text:"Arbeitslager erzeugt einen Arbeiter pro Monat"},
     { key:"#TR_CONFIG_CH_CLAY_PIT_FIRE_RISK_REDUCED", text:"Brandrisiko bei Lehmgruben reduziert"},
     { key:"#TR_CONFIG_CITY_HAS_ANIMALS", text:"Stadt enthält Tiere"},
     { key:"#TR_CONFIG_GOLDMINE_TWICE_PRODUCTION", text:"Goldmine produziert doppelt"},
     { key:"#TR_CONFIG_NEW_TAX_COLLECTION_SYSTEM", text:"Neues Steuereinnahmesystem"},
     { key:"#TR_CONFIG_SMALL_HUT_NOT_CREATE_EMIGRANT", text:"Kleine Hütten erzeugen keine Auswanderer"},
     { key:"#TR_CONFIG_DELIVERY_BOY_GOES_TO_MARKET_ALONE", text:"Läufer geht allein zum Markt"},
     { key:"#TR_CONFIG_RELIGION_COVERAGE_INFLUENCE_SENTIMENT", text:"Religiöse Abdeckung beeinflusst Stimmung"},
     { key:"#TR_CONFIG_MONUMENTS_INFLUENCE_SENTIMENT", text:"Monumente beeinflussen Stimmung"},
     { key:"#TR_CONFIG_WELL_RADIUS_DEPENDS_MOISTURE", text:"Brunnenreichweite hängt von Feuchtigkeit ab"},
     { key:"#TR_CONFIG_ENTER_POINT_ON_NEAREST_TILE", text:"Eingang von Gebäuden auf nächstgelegener Kachel"},
     { key:"#TR_CONFIG_FISHING_WHARF_SPAWN_BOATS", text:"Fischereihafen erzeugt Boote"},
     { key:"#TR_CONFIG_CITY_FLOTSAM_ENABLED", text:"Treibgut in der Stadt aktivieren"},
     { key:"#TR_CONFIG_COPPER_NEAR_MOUNTAINS", text:"Kupfermine darf nahe Bergen gebaut werden"},
     { key:"#TR_CONFIG_RECRUITER_NOT_NEED_FORTS", text:"Rekrutierer benötigen keine Forts"},
     { key:"#TR_CONFIG_BUILDING_CLOSEST_ROAD", text:"Gebäudezugang zur nächsten Straße"},
     { key:"#TR_CONFIG_FLOODPLAIN_RANDOM_GROW", text:"Überschwemmungsgebiete wachsen zufällig"},
     { key:"#TR_CONFIG_DRAW_FPS", text:"FPS anzeigen"},
     { key:"#TR_CONFIG_HIGHLIGHT_TOP_MENU_HOVER", text:"Oberes Menü bei Hover hervorheben"},
     { key:"#TR_CONFIG_EMPIRE_CITY_OLD_NAMES", text:"Alte Städtenamen auf Imperiumskarte anzeigen"},
     { key:"#TR_CONFIG_DRAW_CLOUD_SHADOWS", text:"Wolkenschatten zeichnen (experimentell)"},
     { key:"#TR_CONFIG_HEADER_SCENARIO_CHANGES", text:"Szenarien ändern"},
     { key:"#TR_CONFIG_HEADER_RESOURCES", text:"Rohstoffe ändern"},
     { key:"#TR_CONFIG_ANIMALS", text:"Tiere"},
     { key:"#TR_CONFIG_FLOTSAM", text:"Treibgut"},
     { key:"#TR_GAMEPLAY_GOD_DISABLED", text:"Gott deaktiviert"},
     { key:"#TR_HOTKEY_TITLE", text:"Akhenaten Tastenkombinationen einstellen"},
     { key:"#TR_HOTKEY_LABEL", text:"Tastenkombination"},
     { key:"#TR_HOTKEY_ALTERNATIVE_LABEL", text:"Alternative"},
     { key:"#TR_HOTKEY_HEADER_ARROWS", text:"Pfeiltasten"},
     { key:"#TR_HOTKEY_HEADER_GLOBAL", text:"Globale Tastenkombinationen"},
     { key:"#TR_HOTKEY_HEADER_CITY", text:"Stadt"},
     { key:"#TR_HOTKEY_HEADER_ADVISORS", text:"Berater"},
     { key:"#TR_HOTKEY_HEADER_OVERLAYS", text:"Spezialkarten"},
     { key:"#TR_HOTKEY_HEADER_BOOKMARKS", text:"Lesezeichen für Stadtkarten"},
     { key:"#TR_HOTKEY_HEADER_EDITOR", text:"Editor"},
     { key:"#TR_HOTKEY_HEADER_BUILD", text:"Tastenkürzel für den Bau"},
     { key:"#TR_HOTKEY_ARROW_UP", text:"Hoch"},
     { key:"#TR_HOTKEY_ARROW_DOWN", text:"Runter"},
     { key:"#TR_HOTKEY_ARROW_LEFT", text:"Links"},
     { key:"#TR_HOTKEY_ARROW_RIGHT", text:"Rechts"},
     { key:"#TR_HOTKEY_TOGGLE_FULLSCREEN", text:"Vollbildanzeige an/abschalten"},
     { key:"#TR_HOTKEY_CENTER_WINDOW", text:"Fenster zentrieren"},
     { key:"#TR_HOTKEY_RESIZE_TO_640", text:"Fenstergröße: 640x480"},
     { key:"#TR_HOTKEY_RESIZE_TO_800", text:"Fenstergröße: 800x600"},
     { key:"#TR_HOTKEY_RESIZE_TO_1024", text:"Fenstergröße: 1024x768"},
     { key:"#TR_HOTKEY_SAVE_SCREENSHOT", text:"Screenshot speichern"},
     { key:"#TR_HOTKEY_SAVE_CITY_SCREENSHOT", text:"Stadtweiten Screenshot sp."},
     { key:"#TR_HOTKEY_LOAD_FILE", text:"Datei laden"},
     { key:"#TR_HOTKEY_SAVE_FILE", text:"Datei speichern"},
     { key:"#TR_HOTKEY_INCREASE_GAME_SPEED", text:"Spielgeschwindigkeit erhöhen"},
     { key:"#TR_HOTKEY_DECREASE_GAME_SPEED", text:"Spielgeschwindigkeit reduzieren"},
     { key:"#TR_HOTKEY_TOGGLE_PAUSE", text:"Pause umschalten"},
     { key:"#TR_HOTKEY_CYCLE_LEGION", text:"Durch Legionen wechseln"},
     { key:"#TR_HOTKEY_ROTATE_MAP_LEFT", text:"Karte nach links drehen"},
     { key:"#TR_HOTKEY_ROTATE_MAP_RIGHT", text:"Karte nach rechts drehen"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_LABOR", text:"Berater für Arbeit"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_MILITARY", text:"Berater für Legionen"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_IMPERIAL", text:"Berater für den Imperator"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_RATINGS", text:"Berater für Wertungen"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_TRADE", text:"Berater für Handel"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_POPULATION", text:"Berater für Bevölkerung"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_HEALTH", text:"Berater für Gesundheit"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_EDUCATION", text:"Berater für Bildung"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_ENTERTAINMENT", text:"Berater für Unterhaltung"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_RELIGION", text:"Berater für Religion"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_FINANCIAL", text:"Berater für Finanzen"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_CHIEF", text:"Oberster Berater"},
     { key:"#TR_HOTKEY_SHOW_ADVISOR_HOUSING", text:"Berater für Gebäude"},
     { key:"#TR_HOTKEY_TOGGLE_OVERLAY", text:"Akt. Spezialkarte umschalten"},
     { key:"#TR_HOTKEY_SHOW_OVERLAY_WATER", text:"Wasserkarte"},
     { key:"#TR_HOTKEY_SHOW_OVERLAY_FIRE", text:"Feuerkarte"},
     { key:"#TR_HOTKEY_SHOW_OVERLAY_DAMAGE", text:"Schadenskarte"},
     { key:"#TR_HOTKEY_SHOW_OVERLAY_CRIME", text:"Kriminalitätskarte"},
     { key:"#TR_HOTKEY_ROTATE_BUILDING", text:"Gebäude drehen"},
     { key:"#TR_HOTKEY_SHOW_OVERLAY_PROBLEMS", text:"Problemkarte"},
     { key:"#TR_HOTKEY_GO_TO_BOOKMARK_1", text:"Gehe zu Lesezeichen 1"},
     { key:"#TR_HOTKEY_GO_TO_BOOKMARK_2", text:"Gehe zu Lesezeichen 2"},
     { key:"#TR_HOTKEY_GO_TO_BOOKMARK_3", text:"Gehe zu Lesezeichen 3"},
     { key:"#TR_HOTKEY_GO_TO_BOOKMARK_4", text:"Gehe zu Lesezeichen 4"},
     { key:"#TR_HOTKEY_SET_BOOKMARK_1", text:"Setze Lesezeichen 1"},
     { key:"#TR_HOTKEY_SET_BOOKMARK_2", text:"Setze Lesezeichen 2"},
     { key:"#TR_HOTKEY_SET_BOOKMARK_3", text:"Setze Lesezeichen 3"},
     { key:"#TR_HOTKEY_SET_BOOKMARK_4", text:"Setze Lesezeichen 4"},
     { key:"#TR_HOTKEY_EDITOR_TOGGLE_BATTLE_INFO", text:"Kampfinformationen umschalten"},
     { key:"#TR_HOTKEY_EDIT_TITLE", text:"Drücke neue Tastenkombination"},
     { key:"#TR_BUILDING_ROADBLOCK", text:"Straßensperre"},
     { key:"#TR_BUILDING_ROADBLOCK_DESC", text:"Eine Straßensperre hält herumlungernde Bürger auf."},
     { key:"#TR_HEADER_HOUSING", text:"Wohnraum"},
     { key:"#TR_ADVISOR_HOUSING_ROOM", text:"In der Stadt gibt es noch Wohnraum für"},
     { key:"#TR_ADVISOR_HOUSING_NO_ROOM", text:"In der Stadt gibt es keinen freien Wohnraum."},
     { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_POTTERY", text:"Wohnungen verlangen Keramik"},
     { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_FURNITURE", text:"Wohnungen verlangen Möbel"},
     { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_OIL", text:"Wohnungen verlangen Öl"},
     { key:"#TR_ADVISOR_RESIDENCES_DEMANDING_WINE", text:"Wohnungen verlangen Wein"},
     { key:"#TR_ADVISOR_TOTAL_NUM_HOUSES", text:"Gesamtanzahl an Wohnungen:"},
     { key:"#TR_ADVISOR_AVAILABLE_HOUSING_CAPACITY", text:"Verfügbare Kapazität:"},
     { key:"#TR_ADVISOR_TOTAL_HOUSING_CAPACITY", text:"Gesamtkapazität:"},
     { key:"#TR_ADVISOR_ADVISOR_HEADER_HOUSING", text:"Bevölkerung – Wohnraum"},
     { key:"#TR_ADVISOR_BUTTON_GRAPHS", text:"Diagramme"},
     { key:"#TR_ADVISOR_HOUSING_PROSPERITY_RATING", text:"Wohlstandswert der Wohnungen ist"},
     { key:"#TR_ADVISOR_PERCENTAGE_IN_MANORS", text:"Prozentsatz der Bevölkerung in Villen und Palästen:"},
     { key:"#TR_ADVISOR_PERCENTAGE_IN_SHANTIES", text:"Prozentsatz der Bevölkerung in Zelten und Hütten:"},
     { key:"#TR_ADVISOR_AVERAGE_TAX", text:"Durchschnittlicher Steuerertrag pro Wohnung ist"},
     { key:"#TR_ADVISOR_AVERAGE_AGE", text:"Durchschnittsalter der Bevölkerung ist"},
     { key:"#TR_ADVISOR_PERCENT_IN_WORKFORCE", text:"Prozentsatz der Bevölkerung im Arbeitsleben ist"},
     { key:"#TR_ADVISOR_BIRTHS_LAST_YEAR", text:"Geburten im letzten Jahr:"},
     { key:"#TR_ADVISOR_DEATHS_LAST_YEAR", text:"Todesfälle im letzten Jahr:"},
     { key:"#TR_ADVISOR_TOTAL_POPULATION", text:"Gesamtbevölkerung"},
     { key:"#TR_CONFIG_HEADER_LANGUAGES", lang:"en", text: "Spielsprache"}
]