log_info("akhenaten: localization_it config started")

localization_it = [
     {key:"#TR_NO_PATCH_TITLE", text:"Patch 1.0.1.0 non ??"},
     {key:"#TR_NO_PATCH_MESSAGE", text:""},
     {key:"#TR_MISSING_FONTS_TITLE", text:"Font mancanti"},
     {key:"#TR_MISSING_FONTS_MESSAGE", text:""},
     {key:"#TR_NO_EDITOR_TITLE", text:"Editor non installato"},
     {key:"#TR_NO_EDITOR_MESSAGE", text:"" },
     {key:"#TR_INVALID_LANGUAGE_TITLE", text:"Cartella della lingua non valida"},
     {key:"#TR_INVALID_LANGUAGE_MESSAGE", text:"La cartella selezionata non contiene un pacchetto di lingua corretto. Per favore controlla il log degli errori."},
     {key:"#TR_BUTTON_OK", text:"OK"},
     {key:"#TR_BUTTON_CANCEL", text:"Cancella"},
     {key:"#TR_BUTTON_RESET_DEFAULTS", text:"Ripristina il default"},
     {key:"#TR_BUTTON_CONFIGURE_HOTKEYS", text:"Configura tasti rapidi"},
     {key:"#TR_CONFIG_TITLE", text:"Opzioni di configurazione"},
     {key:"#TR_CONFIG_LANGUAGE_LABEL", text:"Lingua:"},
     {key:"#TR_CONFIG_LANGUAGE_DEFAULT", text:"(default)"},
     {key:"#TR_CONFIG_HEADER_UI_CHANGES", text:"Modifiche all'interfaccia utente"},
     {key:"#TR_CONFIG_HEADER_GAMEPLAY_CHANGES", text:"Modifiche al gioco"},
     {key:"#TR_CONFIG_HEADER_GODS_CHANGES", text:"Gods changes"},
     {key:"#TR_CONFIG_HEADER_BUILDING_CHANGES", text:"Building changes"},
     {key:"#TR_CONFIG_HEADER_RESOURCE_CHANGES", text:"Resource changes"},
     {key:"#TR_CONFIG_SHOW_INTRO_VIDEO", text:"Riproduce il video introduttivo"},
     {key:"#TR_CONFIG_SIDEBAR_INFO", text:"Informazioni extra nel pannello di controllo"},
     {key:"#TR_CONFIG_SMOOTH_SCROLLING", text:"Abilita lo scorrimento continuo"},
     {key:"#TR_CONFIG_VISUAL_FEEDBACK_ON_DELETE", text:"Migliora l'aspetto liberando il terreno"},
     {key:"#TR_CONFIG_ALLOW_CYCLING_TEMPLES", text:"Consente la costruzione di tutti i templi in successione"},
     {key:"#TR_CONFIG_SHOW_WATER_STRUCTURE_RANGE", text:"Mostra la copertura di cisterne, fontane e pozzi"},
     {key:"#TR_CONFIG_SHOW_CONSTRUCTION_SIZE", text:"Mostra le dimensioni della costruzione durante il trascinamento"},
     {key:"#TR_CONFIG_HIGHLIGHT_LEGIONS", text:"Evidenzia la legione al passaggio del cursore"},
     {key:"#TR_CONFIG_FIX_IMMIGRATION_BUG", text:"Corregge il bug dell'immigrazione al livello molto difficile"},
     {key:"#TR_CONFIG_FIX_100_YEAR_GHOSTS", text:"Corregge il bug dei centenari"},
     {key:"#TR_CONFIG_FIX_EDITOR_EVENTS", text:"Elimina le complicazioni al cambio di Imperatore"},
     {key:"#TR_HOTKEY_TITLE", text:"Configurazione delle scorciatoie da tastiera"},
     {key:"#TR_HOTKEY_LABEL", text:"Tasto"},
     {key:"#TR_HOTKEY_ALTERNATIVE_LABEL", text:"Alternativa"},
     {key:"#TR_HOTKEY_HEADER_ARROWS", text:"Frecce"},
     {key:"#TR_HOTKEY_HEADER_GLOBAL", text:"Scorciatoie globali"},
     {key:"#TR_HOTKEY_HEADER_CITY", text:"Scorciatoie per la città"},
     {key:"#TR_HOTKEY_HEADER_ADVISORS", text:"Consiglieri"},
     {key:"#TR_HOTKEY_HEADER_OVERLAYS", text:"Tabelle"},
     {key:"#TR_HOTKEY_HEADER_BOOKMARKS", text:"Segnaposto sulla mappa"},
     {key:"#TR_HOTKEY_HEADER_EDITOR", text:"Editor"},
     {key:"#TR_HOTKEY_HEADER_BUILD", text:"Scorciatoie per costruzione"},
     {key:"#TR_HOTKEY_ARROW_UP", text:"Su"},
     {key:"#TR_HOTKEY_ARROW_DOWN", text:"Giù"},
     {key:"#TR_HOTKEY_ARROW_LEFT", text:"Sinistra"},
     {key:"#TR_HOTKEY_ARROW_RIGHT", text:"Destra"},
     {key:"#TR_HOTKEY_TOGGLE_FULLSCREEN", text:"Tutto schermo"},
     {key:"#TR_HOTKEY_CENTER_WINDOW", text:"Centra la finestra"},
     {key:"#TR_HOTKEY_RESIZE_TO_640", text:"Finestra a 640x480"},
     {key:"#TR_HOTKEY_RESIZE_TO_800", text:"Finestra a 800x600"},
     {key:"#TR_HOTKEY_RESIZE_TO_1024", text:"Finestra a 1024x768"},
     {key:"#TR_HOTKEY_SAVE_SCREENSHOT", text:"Salva l'immagine"},
     {key:"#TR_HOTKEY_SAVE_CITY_SCREENSHOT", text:"Salva l'immagine dell'intera città"},
     {key:"#TR_HOTKEY_LOAD_FILE", text:"Carica file"},
     {key:"#TR_HOTKEY_SAVE_FILE", text:"Salva file"},
     {key:"#TR_HOTKEY_INCREASE_GAME_SPEED", text:"Aumenta la velocità"},
     {key:"#TR_HOTKEY_DECREASE_GAME_SPEED", text:"Diminuisce la velocità"},
     {key:"#TR_HOTKEY_TOGGLE_PAUSE", text:"Pausa"},
     {key:"#TR_HOTKEY_CYCLE_LEGION", text:"Scorre le legioni"},
     {key:"#TR_HOTKEY_ROTATE_MAP_LEFT", text:"Ruota la mappa a sinistra"},
     {key:"#TR_HOTKEY_ROTATE_MAP_RIGHT", text:"Ruota la mappa a destra"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_LABOR", text:"Consigliere del lavoro"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_MILITARY", text:"Consigliere militare"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_IMPERIAL", text:"Consigliere dell'Impero"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_RATINGS", text:"Consigliere dei livelli"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_TRADE", text:"Consigliere commerciale"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_POPULATION", text:"Consigliere della popolazione"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_HEALTH", text:"Consigliere della sanità"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_EDUCATION", text:"Consigliere dell'educazione"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_ENTERTAINMENT", text:"Consigliere degli intrattenimenti"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_RELIGION", text:"Consigliere religioso"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_FINANCIAL", text:"Consigliere finanziario"},
     {key:"#TR_HOTKEY_SHOW_ADVISOR_CHIEF", text:"Consigliere capo"},
     {key:"#TR_HOTKEY_TOGGLE_OVERLAY", text:"Cambia la tabella corrente"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_WATER", text:"Tabella acqua"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_FIRE", text:"Tabella fuoco"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_DAMAGE", text:"Tabella danni"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_CRIME", text:"Tabella crimine"},
     {key:"#TR_HOTKEY_SHOW_OVERLAY_PROBLEMS", text:"Tabella problemi"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_1", text:"Va al segnaposto 1"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_2", text:"Va al segnaposto 2"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_3", text:"Va al segnaposto 3"},
     {key:"#TR_HOTKEY_GO_TO_BOOKMARK_4", text:"Va al segnaposto 4"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_1", text:"Fissa il segnaposto 1"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_2", text:"Fissa il segnaposto 2"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_3", text:"Fissa il segnaposto 3"},
     {key:"#TR_HOTKEY_SET_BOOKMARK_4", text:"Fissa il segnaposto 4"},
     {key:"#TR_HOTKEY_EDITOR_TOGGLE_BATTLE_INFO", text:"Informazioni sulla battaglia"},
     {key:"#TR_HOTKEY_EDIT_TITLE", text:"Premi un nuovo tasto"}
]